### PR TITLE
11 add domain specific data types for ship situation etc using pydantic models

### PR DESCRIPTION
**Pull request by ClaasRostock**
Added domain specific data types for Ship, Situation etc. using pydantic models.
Changed all code to use the new data types.
Added type hints.
Refactored tests to work with the new data types.
Added tests for reading files and writing files.

### CODE REVIEW

**Comment by ClaasRostock** [comment]
Hi @tomarnepedersen 

I am currently comparing the output files from the tests between commit 
Commit e8c2bba9 (open)
by Claas, 2023-11-23 14:44
and latest commit in this branch
Commit db91fb5e (open)
by Claas, 2023-11-25 01:24

I see there are some small differences in the output files.
Have hence reset this pull request to draft, until I investigated and we are sure that the changes in code do not change the output files (at least not content / number-wise).

**Comment by ClaasRostock** [comment]
ship_traffic_generator.generate_traffic_situations() : Corrected an error I introduced with commit 185418af on 2023-11-25 00:16
lat_lon_0 of the new traffic_situation needs to be set to lat_lon_0 from the encounter settings. It was, though, set to lat_lon_0 from the desired traffic situation (which is usually None). I introduced the error when changing the code to use the new pdantic data types.
Now corrected. Also added a related assertion to the tests to ensure the error does not get introduced again.

**Comment by ClaasRostock** [comment]
Hi @tomarnepedersen ,

this PR contains quite a lot of code changes as I introduced pydantic data classes to serve as domain specific types.
Please have a look whether you feel comfortable with it.

I also introduced type hints, resolving the 177 issues that pyright raised after activating the "reportMissingParameterType" rule in pyproject.toml.

There is one spot in the code where I suspect there might be an error. At least the docstring does not match the return values.
Would be good if you can throw a dedicated glimpse on that.
It is in module encounter.py, function calculate_relative_bearing().
If you search for `@TODO` in the code, you will easily find it.

Best greetings
Claas

**Comment by tomarnepedersen** [comment]
Done a few changes. Performing the merge.

**Pull request merged**
